[package]
name = "mongodb1"
version = "0.1.0"
authors = ["Rishav Bhowmik <bhowmikrishav@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "1.2.0"
futures = "0.3.12"
tokio   = "0.2.x"